# Remember to set the value for the environment variables in the url value below.
# For Azure sovereign cloud, add these parameters in the url:
#  azure.scopes
#     - azure_china: https://ossrdbms-aad.database.chinacloudapi.cn/.default
#     - azure_germany: https://ossrdbms-aad.database.cloudapi.de/.default
#     - azure_us_government: https://ossrdbms-aad.database.usgovcloudapi.net/.default
#     - azure: https://ossrdbms-aad.database.windows.net/.default
#  azure.authorityHost
#     - azure_china: https://login.partner.microsoftonline.cn
#     - azure_germany: https://login.microsoftonline.de
#     - azure_us_government: https://login.microsoftonline.us
#     - azure: https://login.microsoftonline.com
postgresql.jdbc.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?user=${MANAGED_IDENTITY_NAME}&sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin&azure.managedIdentityEnabled=true&azure.clientId=${MANAGED_IDENTITY_CLIENT_ID}
# Comment out all content about "username" and "password" because now PostgreSQL will authenticate using managed identity.
# postgresql.jdbc.username=
# postgresql.jdbc.password=

# Example URL for authentication by Service Principal instead of Managed Identity
# postgresql.jdbc.url.service-principal=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?user=${SERVICE_PRINCIPAL_NAME}&sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin&azure.clientId=${SERVICE_PRINCIPAL_CLIENT_ID}&azure.clientSecret=${SERVICE_PRINCIPAL_CLIENT_SECRET}&azure.tenantId=${SERVICE_PRINCIPAL_TENANT_ID}
